var bg_options = [
{ "bg_Text" : "배경을 선택", "bg_Value" : "NULL"},
{ "bg_Text" : "강남역 인근", "bg_Value" : "A1_S1"},
{ "bg_Text" : "역삼 주택가", "bg_Value" : "A1_S2"},
{ "bg_Text" : "시간의 광장", "bg_Value" : "A1_S3"},
{ "bg_Text" : "파괴된 쇼핑몰", "bg_Value" : "A1_S4"},
{ "bg_Text" : "역삼 골목길", "bg_Value" : "A1_S5"},
{ "bg_Text" : "신논현역", "bg_Value" : "A1_S6"},
{ "bg_Text" : "잊혀진 지하철", "bg_Value" : "A2_S1"},
{ "bg_Text" : "구로역 인근", "bg_Value" : "A2_S2"},
{ "bg_Text" : "하늘길", "bg_Value" : "A2_S3"},
{ "bg_Text" : "백화점 내부", "bg_Value" : "A2_S4"},
{ "bg_Text" : "비오는 전철역", "bg_Value" : "A2_S5"},
{ "bg_Text" : "백화점 외부", "bg_Value" : "A2_S6"},
{ "bg_Text" : "마천루 옥상", "bg_Value" : "A2_S7"},
{ "bg_Text" : "신강고등학교 본관", "bg_Value" : "A3_S1"},
{ "bg_Text" : "한강 강변길", "bg_Value" : "A3_S2"},
{ "bg_Text" : "벚꽃길", "bg_Value" : "A3_S3"},
{ "bg_Text" : "신강고등학교 동관", "bg_Value" : "A3_S4"},
{ "bg_Text" : "성수대교", "bg_Value" : "A3_S5"},
{ "bg_Text" : "공원 매표소", "bg_Value" : "A3_S6"},
{ "bg_Text" : "한밤의 대공원", "bg_Value" : "A3_S7"},
{ "bg_Text" : "방과 후의 미궁", "bg_Value" : "A3_SPECIAL"},
{ "bg_Text" : "불타는 강남 광장", "bg_Value" : "A4_S1"},
{ "bg_Text" : "차원간섭 발생지", "bg_Value" : "A4_S2"},
{ "bg_Text" : "강남 대로변", "bg_Value" : "A4_S3"},
{ "bg_Text" : "공중 정찰로", "bg_Value" : "A4_S4"},
{ "bg_Text" : "오염된 시가지", "bg_Value" : "A4_S5"},
{ "bg_Text" : "헬리포트", "bg_Value" : "A4_S6"},
{ "bg_Text" : "유니온 터릿", "bg_Value" : "A4_S7"},
{ "bg_Text" : "용의 전초기지", "bg_Value" : "A4_S8"},
{ "bg_Text" : "용의 궁전", "bg_Value" : "A4_SPECIAL"},
{ "bg_Text" : "공항 외부", "bg_Value" : "A5_S1"},
{ "bg_Text" : "여객터미널", "bg_Value" : "A5_S2"},
{ "bg_Text" : "탑승동 외부", "bg_Value" : "A5_S3"},
{ "bg_Text" : "탑승동 내부", "bg_Value" : "A5_S4"},
{ "bg_Text" : "공항폐쇄구역", "bg_Value" : "A5_S5"},
{ "bg_Text" : "폐쇄구역 외부", "bg_Value" : "A5_S6"},
{ "bg_Text" : "공중 방어전", "bg_Value" : "A7_S1"},
{ "bg_Text" : "석양의 공중전", "bg_Value" : "A7_S2"},
{ "bg_Text" : "비밀 군수공장", "bg_Value" : "A7_S3"},
{ "bg_Text" : "군수물자 운반로", "bg_Value" : "A7_S4"},
{ "bg_Text" : "채굴용 갱도", "bg_Value" : "A7_S5"},
{ "bg_Text" : "광산 심장부", "bg_Value" : "A7_S6"},
{ "bg_Text" : "불타는 뉴욕 광장", "bg_Value" : "A8_S1"},
{ "bg_Text" : "지휘본부 방어전", "bg_Value" : "A8_S2"},
{ "bg_Text" : "뉴욕 중심가", "bg_Value" : "A8_S3"},
{ "bg_Text" : "유니온 타워 진입로", "bg_Value" : "A8_S4"},
{ "bg_Text" : "대파된 램스키퍼", "bg_Value" : "A8_S5"},
{ "bg_Text" : "램스키퍼 함교", "bg_Value" : "A8_S6"},
{ "bg_Text" : "암흑의 거리", "bg_Value" : "A8_S7"},
{ "bg_Text" : "유니온 타워 옥상", "bg_Value" : "A8_S8"},
{ "bg_Text" : "사냥꾼의 밤", "bg_Value" : "A9_S0"},
{ "bg_Text" : "사냥터지기 성(검은양)", "bg_Value" : "A9_S1"},
{ "bg_Text" : "침묵의 복도(검은양)", "bg_Value" : "A9_S2"},
{ "bg_Text" : "지하 연구실(검은양)", "bg_Value" : "A9_S3"},
{ "bg_Text" : "성의 정원(검은양)", "bg_Value" : "A9_S4"},
{ "bg_Text" : "자정의 고성(검은양)", "bg_Value" : "A9_S5"},
{ "bg_Text" : "사냥꾼의 전당(검은양)", "bg_Value" : "A9_S6"},
{ "bg_Text" : "인공 배양실(검은양)", "bg_Value" : "A9_S7"},
{ "bg_Text" : "호프만의 연구실(검은양)", "bg_Value" : "A9_S8"},
{ "bg_Text" : "사냥터지기 성(사냥터지기)", "bg_Value" : "A9_H1"},
{ "bg_Text" : "노을의 고성", "bg_Value" : "A9_H2"},
{ "bg_Text" : "성의 정원", "bg_Value" : "A9_H3"},
{ "bg_Text" : "BIMF광장 낮", "bg_Value" : "A10_S1"},
{ "bg_Text" : "옥상공원 낮", "bg_Value" : "A10_S2"},
{ "bg_Text" : "광안대교 낮", "bg_Value" : "A10_S3"},
{ "bg_Text" : "감만부두 밤", "bg_Value" : "A10_S4"},
{ "bg_Text" : "결전프로그램: 장미숙", "bg_Value" : "A10_S5"},
{ "bg_Text" : "옥상공원 : 미혹", "bg_Value" : "A10_S7"},
{ "bg_Text" : "BIMF광장 : 불신", "bg_Value" : "A10_S8"},
{ "bg_Text" : "감만부두 : 의심", "bg_Value" : "A10_S9"},
{ "bg_Text" : "광안대교 : 폐목", "bg_Value" : "A10_S10"},
{ "bg_Text" : "이벤트 : 할로윈(필드)", "bg_Value" : "E_HALLOWEEN"},
{ "bg_Text" : "이벤트 : 할로윈(사냥꾼의 밤)", "bg_Value" : "E_HALLOWEEN2"},
{ "bg_Text" : "이벤트 : 여름바다", "bg_Value" : "E_HOT"},
{ "bg_Text" : "이벤트 : 2018봄", "bg_Value" : "E_MAY"},
{ "bg_Text" : "이벤트 : 발렌타인", "bg_Value" : "E_VALENTINE"},
{ "bg_Text" : "이벤트 : 4월", "bg_Value" : "E_APRIL"},
{ "bg_Text" : "마이룸", "bg_Value" : "E_MYROOM"} 
]